name: bro_app
description: The Digital Corner Store for Global Brotherhood.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^13.1.0
  
  # Backend & Auth
  supabase_flutter: ^2.3.4
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0 # For that pulsing pulse effect
  image_picker: ^1.1.2
  timeago: ^3.7.0
  
  # Infrastructure
  geolocator: ^11.0.0
  zego_uikit_prebuilt_call: ^4.15.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bro_logo.png
